<?xml version="1.0"?>
<TYPE Type="String" UI="Edit" Version="0.5" State="modified">
  <DEFINITION Label="BaseCha2" Value="BaseCha2"/>
  <DEFINITION Label="MaxCha2" Value="MaxCha2"/>
  <DEFINITION Label="Cha2Modifier" Value="Cha2Modifier"/>
  <DEFINITION Label="CurrentCha2" Value="CurrentCha2"/>
  <DEFINITION Label="BaseCha2Regenerate" Value="BaseCha2Regenerate"/>
  <DEFINITION Label="Cha2RegenerateModifier" Value="Cha2RegenerateModifier"/>
  <DEFINITION Label="CurrentCha2Regenerate" Value="CurrentCha2Regenerate"/>
  <DEFINITION Label="BaseCha2RegenerateRate" Value="BaseCha2RegenerateRate"/>
  <DEFINITION Label="Cha2RegenerateModifierRate" Value="Cha2RegenerateModifierRate"/>
  <DEFINITION Label="CurrentCha2RegenerateRate" Value="CurrentCha2RegenerateRate"/>
  <DEFINITION Label="BaseCha1" Value="BaseCha1"/>
  <DEFINITION Label="MaxCha1" Value="MaxCha1"/>
  <DEFINITION Label="Cha1Modifier" Value="Cha1Modifier"/>
  <DEFINITION Label="CurrentCha1" Value="CurrentCha1"/>
  <DEFINITION Label="BaseCha1Regenerate" Value="BaseCha1Regenerate"/>
  <DEFINITION Label="Cha1RegenerateModifier" Value="Cha1RegenerateModifier"/>
  <DEFINITION Label="CurrentCha1Regenerate" Value="CurrentCha1Regenerate"/>
  <DEFINITION Label="BaseCha1RegenerateRate" Value="BaseCha1RegenerateRate"/>
  <DEFINITION Label="Cha1RegenerateModifierRate" Value="Cha1RegenerateModifierRate"/>
  <DEFINITION Label="CurrentCha1RegenerateRate" Value="CurrentCha1RegenerateRate"/>
  <DEFINITION Label="BaseAgility" Value="BaseAgility"/>
  <DEFINITION Label="MaxAgility" Value="MaxAgility"/>
  <DEFINITION Label="AgilityModifier" Value="AgilityModifier"/>
  <DEFINITION Label="CurrentAgility" Value="CurrentAgility"/>
  <DEFINITION Label="BaseAgilityRegenerate" Value="BaseAgilityRegenerate"/>
  <DEFINITION Label="AgilityRegenerateModifier" Value="AgilityRegenerateModifier"/>
  <DEFINITION Label="CurrentAgilityRegenerate" Value="CurrentAgilityRegenerate"/>
  <DEFINITION Label="BaseAgilityRegenerateRate" Value="BaseAgilityRegenerateRate"/>
  <DEFINITION Label="AgilityRegenerateModifierRate" Value="AgilityRegenerateModifierRate"/>
  <DEFINITION Label="CurrentAgilityRegenerateRate" Value="CurrentAgilityRegenerateRate"/>
  <DEFINITION Label="BaseCha4Reg" Value="BaseCha4Reg"/>
  <DEFINITION Label="MaxCha4Reg" Value="MaxCha4Reg"/>
  <DEFINITION Label="Cha4RegModifier" Value="Cha4RegModifier"/>
  <DEFINITION Label="CurrentCha4Reg" Value="CurrentCha4Reg"/>
  <DEFINITION Label="BaseCha4RegRegenerate" Value="BaseCha4RegRegenerate"/>
  <DEFINITION Label="Cha4RegRegenerateModifier" Value="Cha4RegRegenerateModifier"/>
  <DEFINITION Label="CurrentCha4RegRegenerate" Value="CurrentCha4RegRegenerate"/>
  <DEFINITION Label="BaseCha4RegRegenerateRate" Value="BaseCha4RegRegenerateRate"/>
  <DEFINITION Label="Cha4RegRegenerateModifierRate" Value="Cha4RegRegenerateModifierRate"/>
  <DEFINITION Label="CurrentCha4RegRegenerateRate" Value="CurrentCha4RegRegenerateRate"/>
  <DEFINITION Label="BaseCha2Reg" Value="BaseCha2Reg"/>
  <DEFINITION Label="MaxCha2Reg" Value="MaxCha2Reg"/>
  <DEFINITION Label="Cha2RegModifier" Value="Cha2RegModifier"/>
  <DEFINITION Label="CurrentCha2Reg" Value="CurrentCha2Reg"/>
  <DEFINITION Label="BaseCha2RegRegenerate" Value="BaseCha2RegRegenerate"/>
  <DEFINITION Label="Cha2RegRegenerateModifier" Value="Cha2RegRegenerateModifier"/>
  <DEFINITION Label="CurrentCha2RegRegenerate" Value="CurrentCha2RegRegenerate"/>
  <DEFINITION Label="BaseCha2RegRegenerateRate" Value="BaseCha2RegRegenerateRate"/>
  <DEFINITION Label="Cha2RegRegenerateModifierRate" Value="Cha2RegRegenerateModifierRate"/>
  <DEFINITION Label="CurrentCha2RegRegenerateRate" Value="CurrentCha2RegRegenerateRate"/>
  <DEFINITION Label="BaseCha3" Value="BaseCha3"/>
  <DEFINITION Label="MaxCha3" Value="MaxCha3"/>
  <DEFINITION Label="Cha3Modifier" Value="Cha3Modifier"/>
  <DEFINITION Label="CurrentCha3" Value="CurrentCha3"/>
  <DEFINITION Label="BaseCha3Regenerate" Value="BaseCha3Regenerate"/>
  <DEFINITION Label="Cha3RegenerateModifier" Value="Cha3RegenerateModifier"/>
  <DEFINITION Label="CurrentCha3Regenerate" Value="CurrentCha3Regenerate"/>
  <DEFINITION Label="BaseCha3RegenerateRate" Value="BaseCha3RegenerateRate"/>
  <DEFINITION Label="Cha3RegenerateModifierRate" Value="Cha3RegenerateModifierRate"/>
  <DEFINITION Label="CurrentCha3RegenerateRate" Value="CurrentCha3RegenerateRate"/>
  <DEFINITION Label="BaseCharisme" Value="BaseCharisme"/>
  <DEFINITION Label="MaxCharisme" Value="MaxCharisme"/>
  <DEFINITION Label="CharismeModifier" Value="CharismeModifier"/>
  <DEFINITION Label="CurrentCharisme" Value="CurrentCharisme"/>
  <DEFINITION Label="BaseCharismeRegenerate" Value="BaseCharismeRegenerate"/>
  <DEFINITION Label="CharismeRegenerateModifier" Value="CharismeRegenerateModifier"/>
  <DEFINITION Label="CurrentCharismeRegenerate" Value="CurrentCharismeRegenerate"/>
  <DEFINITION Label="BaseCharismeRegenerateRate" Value="BaseCharismeRegenerateRate"/>
  <DEFINITION Label="CharismeRegenerateModifierRate" Value="CharismeRegenerateModifierRate"/>
  <DEFINITION Label="CurrentCharismeRegenerateRate" Value="CurrentCharismeRegenerateRate"/>
  <DEFINITION Label="BaseEmpathie" Value="BaseEmpathie"/>
  <DEFINITION Label="MaxEmpathie" Value="MaxEmpathie"/>
  <DEFINITION Label="EmpathieModifier" Value="EmpathieModifier"/>
  <DEFINITION Label="CurrentEmpathie" Value="CurrentEmpathie"/>
  <DEFINITION Label="BaseEmpathieRegenerate" Value="BaseEmpathieRegenerate"/>
  <DEFINITION Label="EmpathieRegenerateModifier" Value="EmpathieRegenerateModifier"/>
  <DEFINITION Label="CurrentEmpathieRegenerate" Value="CurrentEmpathieRegenerate"/>
  <DEFINITION Label="BaseEmpathieRegenerateRate" Value="BaseEmpathieRegenerateRate"/>
  <DEFINITION Label="EmpathieRegenerateModifierRate" Value="EmpathieRegenerateModifierRate"/>
  <DEFINITION Label="CurrentEmpathieRegenerateRate" Value="CurrentEmpathieRegenerateRate"/>
  <DEFINITION Label="BasePerception" Value="BasePerception"/>
  <DEFINITION Label="MaxPerception" Value="MaxPerception"/>
  <DEFINITION Label="PerceptionModifier" Value="PerceptionModifier"/>
  <DEFINITION Label="CurrentPerception" Value="CurrentPerception"/>
  <DEFINITION Label="BasePerceptionRegenerate" Value="BasePerceptionRegenerate"/>
  <DEFINITION Label="PerceptionRegenerateModifier" Value="PerceptionRegenerateModifier"/>
  <DEFINITION Label="CurrentPerceptionRegenerate" Value="CurrentPerceptionRegenerate"/>
  <DEFINITION Label="BasePerceptionRegenerateRate" Value="BasePerceptionRegenerateRate"/>
  <DEFINITION Label="PerceptionRegenerateModifierRate" Value="PerceptionRegenerateModifierRate"/>
  <DEFINITION Label="CurrentPerceptionRegenerateRate" Value="CurrentPerceptionRegenerateRate"/>
  <DEFINITION Label="SpeedVariationModifier" Value="SpeedVariationModifier"/>
  <DEFINITION Label="WalkSpeed" Value="WalkSpeed"/>
  <DEFINITION Label="RunSpeed" Value="RunSpeed"/>
  <DEFINITION Label="Scores physiques" Value="Scores physiques"/>
  <DEFINITION Label="BaseChaScore1" Value="BaseChaScore1"/>
  <DEFINITION Label="MaxChaScore1" Value="MaxChaScore1"/>
  <DEFINITION Label="ChaScore1Modifier" Value="ChaScore1Modifier"/>
  <DEFINITION Label="CurrentChaScore1" Value="CurrentChaScore1"/>
  <DEFINITION Label="BaseChaScore1Regenerate" Value="BaseChaScore1Regenerate"/>
  <DEFINITION Label="ChaScore1RegenerateModifier" Value="ChaScore1RegenerateModifier"/>
  <DEFINITION Label="CurrentChaScore1Regenerate" Value="CurrentChaScore1Regenerate"/>
  <DEFINITION Label="BaseChaScore1RegenerateRate" Value="BaseChaScore1RegenerateRate"/>
  <DEFINITION Label="ChaScore1RegenerateModifierRate" Value="ChaScore1RegenerateModifierRate"/>
  <DEFINITION Label="CurrentChaScore1RegenerateRate" Value="CurrentChaScore1RegenerateRate"/>
  <DEFINITION Label="BaseChaScore3" Value="BaseChaScore3"/>
  <DEFINITION Label="MaxChaScore3" Value="MaxChaScore3"/>
  <DEFINITION Label="ChaScore3Modifier" Value="ChaScore3Modifier"/>
  <DEFINITION Label="CurrentChaScore3" Value="CurrentChaScore3"/>
  <DEFINITION Label="BaseChaScore3Regenerate" Value="BaseChaScore3Regenerate"/>
  <DEFINITION Label="ChaScore3RegenerateModifier" Value="ChaScore3RegenerateModifier"/>
  <DEFINITION Label="CurrentChaScore3Regenerate" Value="CurrentChaScore3Regenerate"/>
  <DEFINITION Label="BaseChaScore3RegenerateRate" Value="BaseChaScore3RegenerateRate"/>
  <DEFINITION Label="ChaScore3RegenerateModifierRate" Value="ChaScore3RegenerateModifierRate"/>
  <DEFINITION Label="CurrentChaScore3RegenerateRate" Value="CurrentChaScore3RegenerateRate"/>
  <DEFINITION Label="BaseChaScore2" Value="BaseChaScore2"/>
  <DEFINITION Label="MaxChaScore2" Value="MaxChaScore2"/>
  <DEFINITION Label="ChaScore2Modifier" Value="ChaScore2Modifier"/>
  <DEFINITION Label="CurrentChaScore2" Value="CurrentChaScore2"/>
  <DEFINITION Label="BaseChaScore2Regenerate" Value="BaseChaScore2Regenerate"/>
  <DEFINITION Label="ChaScore2RegenerateModifier" Value="ChaScore2RegenerateModifier"/>
  <DEFINITION Label="CurrentChaScore2Regenerate" Value="CurrentChaScore2Regenerate"/>
  <DEFINITION Label="BaseChaScore2RegenerateRate" Value="BaseChaScore2RegenerateRate"/>
  <DEFINITION Label="ChaScore2RegenerateModifierRate" Value="ChaScore2RegenerateModifierRate"/>
  <DEFINITION Label="CurrentChaScore2RegenerateRate" Value="CurrentChaScore2RegenerateRate"/>
  <DEFINITION Label="BaseWeight" Value="BaseWeight"/>
  <DEFINITION Label="MaxWeight" Value="MaxWeight"/>
  <DEFINITION Label="WeightModifier" Value="WeightModifier"/>
  <DEFINITION Label="CurrentWeight" Value="CurrentWeight"/>
  <DEFINITION Label="BaseWeightRegenerate" Value="BaseWeightRegenerate"/>
  <DEFINITION Label="WeightRegenerateModifier" Value="WeightRegenerateModifier"/>
  <DEFINITION Label="CurrentWeightRegenerate" Value="CurrentWeightRegenerate"/>
  <DEFINITION Label="BaseWeightRegenerateRate" Value="BaseWeightRegenerateRate"/>
  <DEFINITION Label="WeightRegenerateModifierRate" Value="WeightRegenerateModifierRate"/>
  <DEFINITION Label="CurrentWeightRegenerateRate" Value="CurrentWeightRegenerateRate"/>
  <DEFINITION Label="BaseDiseaseResist" Value="BaseDiseaseResist"/>
  <DEFINITION Label="MaxDiseaseResist" Value="MaxDiseaseResist"/>
  <DEFINITION Label="DiseaseResistModifier" Value="DiseaseResistModifier"/>
  <DEFINITION Label="CurrentDiseaseResist" Value="CurrentDiseaseResist"/>
  <DEFINITION Label="BaseDiseaseResistRegenerate" Value="BaseDiseaseResistRegenerate"/>
  <DEFINITION Label="DiseaseResistRegenerateModifier" Value="DiseaseResistRegenerateModifier"/>
  <DEFINITION Label="CurrentDiseaseResistRegenerate" Value="CurrentDiseaseResistRegenerate"/>
  <DEFINITION Label="BaseDiseaseResistRegenerateRate" Value="BaseDiseaseResistRegenerateRate"/>
  <DEFINITION Label="DiseaseResistRegenerateModifierRate" Value="DiseaseResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentDiseaseResistRegenerateRate" Value="CurrentDiseaseResistRegenerateRate"/>
  <DEFINITION Label="BaseMagicResist" Value="BaseMagicResist"/>
  <DEFINITION Label="MaxMagicResist" Value="MaxMagicResist"/>
  <DEFINITION Label="MagicResistModifier" Value="MagicResistModifier"/>
  <DEFINITION Label="CurrentMagicResist" Value="CurrentMagicResist"/>
  <DEFINITION Label="BaseMagicResistRegenerate" Value="BaseMagicResistRegenerate"/>
  <DEFINITION Label="MagicResistRegenerateModifier" Value="MagicResistRegenerateModifier"/>
  <DEFINITION Label="CurrentMagicResistRegenerate" Value="CurrentMagicResistRegenerate"/>
  <DEFINITION Label="BaseMagicResistRegenerateRate" Value="BaseMagicResistRegenerateRate"/>
  <DEFINITION Label="MagicResistRegenerateModifierRate" Value="MagicResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentMagicResistRegenerateRate" Value="CurrentMagicResistRegenerateRate"/>
  <DEFINITION Label="BaseTechnoResist" Value="BaseTechnoResist"/>
  <DEFINITION Label="MaxTechnoResist" Value="MaxTechnoResist"/>
  <DEFINITION Label="TechnoResistModifier" Value="TechnoResistModifier"/>
  <DEFINITION Label="CurrentTechnoResist" Value="CurrentTechnoResist"/>
  <DEFINITION Label="BaseTechnoResistRegenerate" Value="BaseTechnoResistRegenerate"/>
  <DEFINITION Label="TechnoResistRegenerateModifier" Value="TechnoResistRegenerateModifier"/>
  <DEFINITION Label="CurrentTechnoResistRegenerate" Value="CurrentTechnoResistRegenerate"/>
  <DEFINITION Label="BaseTechnoResistRegenerateRate" Value="BaseTechnoResistRegenerateRate"/>
  <DEFINITION Label="TechnoResistRegenerateModifierRate" Value="TechnoResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentTechnoResistRegenerateRate" Value="CurrentTechnoResistRegenerateRate"/>
  <DEFINITION Label="BaseImpactResist" Value="BaseImpactResist"/>
  <DEFINITION Label="MaxImpactResist" Value="MaxImpactResist"/>
  <DEFINITION Label="ImpactResistModifier" Value="ImpactResistModifier"/>
  <DEFINITION Label="CurrentImpactResist" Value="CurrentImpactResist"/>
  <DEFINITION Label="BaseImpactResistRegenerate" Value="BaseImpactResistRegenerate"/>
  <DEFINITION Label="ImpactResistRegenerateModifier" Value="ImpactResistRegenerateModifier"/>
  <DEFINITION Label="CurrentImpactResistRegenerate" Value="CurrentImpactResistRegenerate"/>
  <DEFINITION Label="BaseImpactResistRegenerateRate" Value="BaseImpactResistRegenerateRate"/>
  <DEFINITION Label="ImpactResistRegenerateModifierRate" Value="ImpactResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentImpactResistRegenerateRate" Value="CurrentImpactResistRegenerateRate"/>
  <DEFINITION Label="BaseFearResist" Value="BaseFearResist"/>
  <DEFINITION Label="MaxFearResist" Value="MaxFearResist"/>
  <DEFINITION Label="FearResistModifier" Value="FearResistModifier"/>
  <DEFINITION Label="CurrentFearResist" Value="CurrentFearResist"/>
  <DEFINITION Label="BaseFearResistRegenerate" Value="BaseFearResistRegenerate"/>
  <DEFINITION Label="FearResistRegenerateModifier" Value="FearResistRegenerateModifier"/>
  <DEFINITION Label="CurrentFearResistRegenerate" Value="CurrentFearResistRegenerate"/>
  <DEFINITION Label="BaseFearResistRegenerateRate" Value="BaseFearResistRegenerateRate"/>
  <DEFINITION Label="FearResistRegenerateModifierRate" Value="FearResistRegenerateModifierRate"/>
  <DEFINITION Label="CurrentFearResistRegenerateRate" Value="CurrentFearResistRegenerateRate"/>
  <DEFINITION Label="Harvest" Value="Harvest"/>
  <DEFINITION Label="Quartering" Value="Quartering"/>
  <DEFINITION Label="Fishing" Value="Fishing"/>
  <DEFINITION Label="Diving" Value="Diving"/>
  <DEFINITION Label="Digging" Value="Digging"/>
  <DEFINITION Label="Desert" Value="Desert"/>
  <DEFINITION Label="Jungle" Value="Jungle"/>
  <DEFINITION Label="Lake" Value="Lake"/>
  <DEFINITION Label="PrimaryRoots" Value="PrimaryRoots"/>
  <DEFINITION Label="FirstAid" Value="FirstAid"/>
  <DEFINITION Label="HominOpponentConsider" Value="HominOpponentConsider"/>
  <DEFINITION Label="Camouflage" Value="Camouflage"/>
  <DEFINITION Label="Fyros" Value="Fyros"/>
  <DEFINITION Label="Tryker" Value="Tryker"/>
  <DEFINITION Label="Matis" Value="Matis"/>
  <DEFINITION Label="Zorai" Value="Zorai"/>
  <DEFINITION Label="Kitin" Value="Kitin"/>
  <DEFINITION Label="Dragon" Value="Dragon"/>
  <DEFINITION Label="TrainingCha2" Value="TrainingCha2"/>
  <DEFINITION Label="TrainingCha1" Value="TrainingCha1"/>
  <DEFINITION Label="TrainingAgility" Value="TrainingAgility"/>
  <DEFINITION Label="TrainingPerception" Value="TrainingPerception"/>
  <DEFINITION Label="TrainingCha4Reg" Value="TrainingCha4Reg"/>
  <DEFINITION Label="TrainingCha2Reg" Value="TrainingCha2Reg"/>
  <DEFINITION Label="TrainingCha3" Value="TrainingCha3"/>
  <DEFINITION Label="TrainingEmpathie" Value="TrainingEmpathie"/>
  <DEFINITION Label="TrainingChaScore1" Value="TrainingChaScore1"/>
  <DEFINITION Label="TrainingChaScore3" Value="TrainingChaScore3"/>
  <DEFINITION Label="TrainingChaScore2" Value="TrainingChaScore2"/>
  <DEFINITION Label="TrainingMagicResist" Value="TrainingMagicResist"/>
  <DEFINITION Label="TrainingImpactResist" Value="TrainingImpactResist"/>
  <DEFINITION Label="TrainingDiseaseResist" Value="TrainingDiseaseResist"/>
  <DEFINITION Label="TrainingTechnoResist" Value="TrainingTechnoResist"/>
  <DEFINITION Label="TrainingFearResist" Value="TrainingFearResist"/>
  <DEFINITION Label="Caravan" Value="Caravan"/>
  <DEFINITION Label="Rocktabou" Value="Rocktabou"/>
  <DEFINITION Label="Goo" Value="Goo"/>
  <DEFINITION Label="Kami" Value="Kami"/>
  <DEFINITION Label="TrykerMystery" Value="TrykerMystery"/>
  <DEFINITION Label="MatisMystery" Value="MatisMystery"/>
  <DEFINITION Label="ZoraiMystery" Value="ZoraiMystery"/>
  <DEFINITION Label="Dagger" Value="Dagger"/>
  <DEFINITION Label="Sword" Value="Sword"/>
  <DEFINITION Label="LongSword" Value="LongSword"/>
  <DEFINITION Label="TwoHandsSword" Value="TwoHandsSword"/>
  <DEFINITION Label="Saber" Value="Saber"/>
  <DEFINITION Label="Axe" Value="Axe"/>
  <DEFINITION Label="Mass" Value="Mass"/>
  <DEFINITION Label="Stick" Value="Stick"/>
  <DEFINITION Label="GreatAxe" Value="GreatAxe"/>
  <DEFINITION Label="GreatMass" Value="GreatMass"/>
  <DEFINITION Label="Pike" Value="Pike"/>
  <DEFINITION Label="HandToHand" Value="HandToHand"/>
  <DEFINITION Label="BersekAttack" Value="BersekAttack"/>
  <DEFINITION Label="Kick" Value="Kick"/>
  <DEFINITION Label="OnHorseBackMelee" Value="OnHorseBackMelee"/>
  <DEFINITION Label="Rondache" Value="Rondache"/>
  <DEFINITION Label="Shield" Value="Shield"/>
  <DEFINITION Label="DualWield" Value="DualWield"/>
  <DEFINITION Label="Dodging" Value="Dodging"/>
  <DEFINITION Label="HeavyArmourWear" Value="HeavyArmourWear"/>
  <DEFINITION Label="MediumArmourWear" Value="MediumArmourWear"/>
  <DEFINITION Label="LightArmourWear" Value="LightArmourWear"/>
  <DEFINITION Label="FyrosSword" Value="FyrosSword"/>
  <DEFINITION Label="FyrosLongSword" Value="FyrosLongSword"/>
  <DEFINITION Label="FyrosTwoHandSword" Value="FyrosTwoHandSword"/>
  <DEFINITION Label="FyrosSaber" Value="FyrosSaber"/>
  <DEFINITION Label="FyrosDagger" Value="FyrosDagger"/>
  <DEFINITION Label="FyrosHeavyArmourWear" Value="FyrosHeavyArmourWear"/>
  <DEFINITION Label="FyrosMediumArmourWear" Value="FyrosMediumArmourWear"/>
  <DEFINITION Label="FyrosLightArmourWear" Value="FyrosLightArmourWear"/>
  <DEFINITION Label="FyrosShield" Value="FyrosShield"/>
  <DEFINITION Label="FyrosRondach" Value="FyrosRondach"/>
  <DEFINITION Label="BowPistol" Value="BowPistol"/>
  <DEFINITION Label="BowRifle" Value="BowRifle"/>
  <DEFINITION Label="Pistol" Value="Pistol"/>
  <DEFINITION Label="Rifle" Value="Rifle"/>
  <DEFINITION Label="HeavyWeapon" Value="HeavyWeapon"/>
  <DEFINITION Label="Rocket" Value="Rocket"/>
  <DEFINITION Label="Grenade" Value="Grenade"/>
  <DEFINITION Label="OnHorseBackShoot" Value="OnHorseBackShoot"/>
  <DEFINITION Label="FyrosBowPistol" Value="FyrosBowPistol"/>
  <DEFINITION Label="FyrosRifle" Value="FyrosRifle"/>
  <DEFINITION Label="FyrosPistol" Value="FyrosPistol"/>
  <DEFINITION Label="Mandragore" Value="Mandragore"/>
  <DEFINITION Label="Dryade" Value="Dryade"/>
  <DEFINITION Label="Sylve" Value="Sylve"/>
  <DEFINITION Label="MajorMandragore" Value="MajorMandragore"/>
  <DEFINITION Label="MajorDryade" Value="MajorDryade"/>
  <DEFINITION Label="MajorSylve" Value="MajorSylve"/>
  <DEFINITION Label="MagicTransfert" Value="MagicTransfert"/>
  <DEFINITION Label="MagicObjects" Value="MagicObjects"/>
  <DEFINITION Label="MandragoreSpring" Value="MandragoreSpring"/>
  <DEFINITION Label="MandragoreSummer" Value="MandragoreSummer"/>
  <DEFINITION Label="MandragoreAutomn" Value="MandragoreAutomn"/>
  <DEFINITION Label="MandragoreWinter" Value="MandragoreWinter"/>
  <DEFINITION Label="SylveSpring" Value="SylveSpring"/>
  <DEFINITION Label="SylveSummer" Value="SylveSummer"/>
  <DEFINITION Label="SylveAutomn" Value="SylveAutomn"/>
  <DEFINITION Label="SylveWinter" Value="SylveWinter"/>
  <DEFINITION Label="DryadeSpring" Value="DryadeSpring"/>
  <DEFINITION Label="DryadeSummer" Value="DryadeSummer"/>
  <DEFINITION Label="DryadeAutomn" Value="DryadeAutomn"/>
  <DEFINITION Label="DryadeWinter" Value="DryadeWinter"/>
  <DEFINITION Label="MajorMandragoreSpring" Value="MajorMandragoreSpring"/>
  <DEFINITION Label="MajorMandragoreSummer" Value="MajorMandragoreSummer"/>
  <DEFINITION Label="MajorMandragoreAutomn" Value="MajorMandragoreAutomn"/>
  <DEFINITION Label="MajorMandragoreWinter" Value="MajorMandragoreWinter"/>
  <DEFINITION Label="MajorSylveSpring" Value="MajorSylveSpring"/>
  <DEFINITION Label="MajorSylveSummer" Value="MajorSylveSummer"/>
  <DEFINITION Label="MajorSylveAutomn" Value="MajorSylveAutomn"/>
  <DEFINITION Label="MajorSylveWinter" Value="MajorSylveWinter"/>
  <DEFINITION Label="MajorDryadeSpring" Value="MajorDryadeSpring"/>
  <DEFINITION Label="MajorDryadeSummer" Value="MajorDryadeSummer"/>
  <DEFINITION Label="MajorDryadeAutomn" Value="MajorDryadeAutomn"/>
  <DEFINITION Label="MajorDryadeWinter" Value="MajorDryadeWinter"/>
  <DEFINITION Label="Running" Value="Running"/>
  <DEFINITION Label="Swimming" Value="Swimming"/>
  <DEFINITION Label="Riding" Value="Riding"/>
  <DEFINITION Label="TrainAnimal" Value="TrainAnimal"/>
  <DEFINITION Label="LeadAnimal" Value="LeadAnimal"/>
  <DEFINITION Label="WeaponsCutting" Value="WeaponsCutting"/>
  <DEFINITION Label="MakeThrowingWeapons" Value="MakeThrowingWeapons"/>
  <DEFINITION Label="Blacksmithing" Value="Blacksmithing"/>
  <DEFINITION Label="ClothTailoring" Value="ClothTailoring"/>
  <DEFINITION Label="LeatherTailoring" Value="LeatherTailoring"/>
  <DEFINITION Label="Jewellery" Value="Jewellery"/>
  <DEFINITION Label="Cooking" Value="Cooking"/>
  <DEFINITION Label="Mechanic" Value="Mechanic"/>
  <DEFINITION Label="Building" Value="Building"/>
  <DEFINITION Label="Apothecary" Value="Apothecary"/>
  <DEFINITION Label="MakeShiftRepair" Value="MakeShiftRepair"/>
  <DEFINITION Label="ArmorAndWeaponSmithing" Value="ArmorAndWeaponSmithing"/>
  <DEFINITION Label="Slots d'equipements" Value="Slots d'equipements"/>
  <DEFINITION Label="Headdress" Value="Headdress"/>
  <DEFINITION Label="Head" Value="Head"/>
  <DEFINITION Label="Face" Value="Face"/>
  <DEFINITION Label="EarL" Value="EarL"/>
  <DEFINITION Label="EarR" Value="EarR"/>
  <DEFINITION Label="Neck" Value="Neck"/>
  <DEFINITION Label="Shoulders" Value="Shoulders"/>
  <DEFINITION Label="Back" Value="Back"/>
  <DEFINITION Label="Chest" Value="Chest"/>
  <DEFINITION Label="Arms" Value="Arms"/>
  <DEFINITION Label="WristL" Value="WristL"/>
  <DEFINITION Label="WristR" Value="WristR"/>
  <DEFINITION Label="Hands" Value="Hands"/>
  <DEFINITION Label="HandL" Value="HandL"/>
  <DEFINITION Label="HandR" Value="HandR"/>
  <DEFINITION Label="FingerL" Value="FingerL"/>
  <DEFINITION Label="FingerR" Value="FingerR"/>
  <DEFINITION Label="Legs" Value="Legs"/>
  <DEFINITION Label="AnkleL" Value="AnkleL"/>
  <DEFINITION Label="AnkleR" Value="AnkleR"/>
  <DEFINITION Label="Feets" Value="Feets"/>
  <DEFINITION Label="ChaScore1" Value="ChaScore1"/>
  <LOG>Mon Jun 17 18:07:16 2002 (miller) Type Predef = 
Mon Jun 17 18:07:16 2002 (miller) Type Type = String
Mon Jun 17 18:07:16 2002 (miller) Type UI = NonEditableCombo
Wed Jul 24 15:22:26 2002 (chafik) Type UI = Edit
Fri Jul 26 14:03:31 2002 (chafik) Type Predef = 
Fri Jul 26 14:03:35 2002 (chafik) Type Predef = 
Fri Jul 26 14:35:23 2002 (chafik) Type Predef = </LOG>
</TYPE>
